//
//  WeatherDataDisplayPresenter.swift
//  WeatherApp
//
//  Created by Kinjal Solanki on 22/03/19.
//  Copyright (c) 2019 Kinjal Solanki. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Networking

protocol WeatherDataDisplayPresentationProtocol {
    func getWeatherReponse(mdlResponse: [ResponseModel])
    func callWeatherApi(urlString: String)
    func initiateApiCalls()
}

class WeatherDataDisplayPresenter: WeatherDataDisplayPresentationProtocol {
    
    weak var viewController: WeatherDataDisplayProtocol?
    var interactor: WeatherDataDisplayInteractorProtocol?
    
    // MARK: Get weather response
    func getWeatherReponse(mdlResponse: [ResponseModel]) {
        self.viewController?.displayResponse(mdlResponse: mdlResponse)
    }
    
    func callWeatherApi(urlString: String) {
        self.interactor?.getWeatherData(urlString: urlString)
    }
    
    func initiateApiCalls() {
        self.interactor?.initiateApiCalls()
    }
    
}
